export const SET_LANG = "SET_LANG";
export const REFRESH_LIST = "REFRESH_LIST";

export const SET_LOCATION = "SET_LOCATION";
export const RESET_LOCATION = "RESET_LOCATION";
export const SET_LOCATION_PROVIDER_STATUS = "SET_LOCATION_PROVIDER_STATUS";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FB_FAIL = "LOGIN_FB_FAIL";
export const LOGIN_RESET_ERROR = "LOGIN_RESET_ERROR";
export const LOGOUT = "LOGOUT";
export const SELECT_TAB = "SELECT_TAB";
export const REQUEST_SEC_LOCATION = "REQUEST_SEC_LOCATION";
export const SUCCESS_SEC_LOCATION = "SUCCESS_SEC_LOCATION";
export const SUCCESS_ADDRESS_TYPES = "SUCCESS_ADDRESS_TYPES";

export const SET_COUPON = "SET_COUPON";
export const SET_CART_COUNT = "SET_CART_COUNT";

